### ISSUE TITLE
Step fails with error bundler: failed to load command: test-cloud

### ISSUE THREAD

**Issue by adnxsmob1** [bitrise-steplib/steps-xamarin-test-cloud-for-calabash-ios#10]
bundle exec test-cloud submit "****" *** --user=*** --devices=409dd72c --series=master --locale="en_US" --app-name="***"
bundler: failed to load command: test-cloud (/usr/local/bin/test-cloud)
Bundler::GemNotFound: Your bundle is locked to CFPropertyList (2.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of CFPropertyList (2.3.5) has removed it. You'll need to update your bundle to a different version of CFPropertyList (2.3.5) that hasn't been removed in order to install.

**Comment by adnxsmob1** [comment]
+------------------------------------------------------------------------------+
| (7) xamarin-test-cloud-for-calabash-ios@0.9.4                                |
+------------------------------------------------------------------------------+
| id: xamarin-test-cloud-for-calabash-ios                                      |
| version: 0.9.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-03-09T21:16:10-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |

========== Configs ==========
 * ipa_path: ***
 * dsym_path: 
 * api_key: ***
 * user: ***
 * devices: 409dd72c
 * async: false
 * series: master
 * other_parameters: --locale="en_US" --app-name="***"
Gemfile found, but no calabash-cucumber and/or xamarin-test-cloud gem specified
Installing missings gems
gem install calabash-cucumber
Couldn't find file to include 'Contributing.rdoc' from README.rdoc
Couldn't find file to include 'License.rdoc' from README.rdoc
Successfully installed gherkin-4.0.0
Successfully installed cucumber-core-1.5.0
Successfully installed builder-3.2.3
Successfully installed diff-lcs-1.3
Successfully installed multi_test-0.1.2
Successfully installed cucumber-wire-0.0.1
Successfully installed cucumber-2.4.0
Successfully installed edn-1.1.1

*****************************************************************
* To use the slowhandcuke formatter, simple add                 *
*   --format 'Slowhandcuke::Formatter'                          * 
* to your cucumber.yml, Rakefile, or command line call          *
*****************************************************************

Successfully installed slowhandcuke-0.0.3
Successfully installed geocoder-1.4.3
Successfully installed clipboard-1.1.1
Successfully installed awesome_print-1.7.0
Successfully installed thor-0.19.4
Successfully installed command_runner_ng-0.1.0
Successfully installed run_loop-2.3.1
Successfully installed calabash-cucumber-0.20.4
Parsing documentation for gherkin-4.0.0
Installing ri documentation for gherkin-4.0.0
Parsing documentation for cucumber-core-1.5.0
Installing ri documentation for cucumber-core-1.5.0
Parsing documentation for builder-3.2.3
Installing ri documentation for builder-3.2.3
Parsing documentation for diff-lcs-1.3
Installing ri documentation for diff-lcs-1.3
Parsing documentation for multi_test-0.1.2
Installing ri documentation for multi_test-0.1.2
Parsing documentation for cucumber-wire-0.0.1
Installing ri documentation for cucumber-wire-0.0.1
Parsing documentation for cucumber-2.4.0
Installing ri documentation for cucumber-2.4.0
Parsing documentation for edn-1.1.1
Installing ri documentation for edn-1.1.1
Parsing documentation for slowhandcuke-0.0.3
Installing ri documentation for slowhandcuke-0.0.3
Parsing documentation for geocoder-1.4.3
Installing ri documentation for geocoder-1.4.3
Parsing documentation for clipboard-1.1.1
Installing ri documentation for clipboard-1.1.1
Parsing documentation for awesome_print-1.7.0
Installing ri documentation for awesome_print-1.7.0
Parsing documentation for thor-0.19.4
Installing ri documentation for thor-0.19.4
Parsing documentation for command_runner_ng-0.1.0
Installing ri documentation for command_runner_ng-0.1.0
Parsing documentation for run_loop-2.3.1
Installing ri documentation for run_loop-2.3.1
Parsing documentation for calabash-cucumber-0.20.4
Installing ri documentation for calabash-cucumber-0.20.4
Done installing documentation for gherkin, cucumber-core, builder, diff-lcs, multi_test, cucumber-wire, cucumber, edn, slowhandcuke, geocoder, clipboard, awesome_print, thor, command_runner_ng, run_loop, calabash-cucumber after 22 seconds
16 gems installed
gem install xamarin-test-cloud
Successfully installed retriable-2.0.2
Successfully installed mime-types-2.99.3
Successfully installed xamarin-test-cloud-2.1.2
Parsing documentation for retriable-2.0.2
Installing ri documentation for retriable-2.0.2
Parsing documentation for mime-types-2.99.3
Installing ri documentation for mime-types-2.99.3
Parsing documentation for xamarin-test-cloud-2.1.2
Installing ri documentation for xamarin-test-cloud-2.1.2
Done installing documentation for retriable, mime-types, xamarin-test-cloud after 1 seconds
3 gems installed

bundle exec test-cloud submit "***" *** --user=*** --devices=409dd72c --series=master --locale="en_US" --app-name="***"
bundler: failed to load command: test-cloud (/usr/local/bin/test-cloud)
Bundler::GemNotFound: Your bundle is locked to CFPropertyList (2.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of CFPropertyList (2.3.5) has removed it. You'll need to update your bundle to a different version of CFPropertyList (2.3.5) that hasn't been removed in order to install.
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
test-cloud -- failed

**Comment by godrei** [comment]
Hi @adnxsmob1 , 
thanks for the report!

The issue source is: the step finds a gemfile, and tries to run the test cloud command through bundler, even the gemfile does not contain test cloud related gems (or does not contain both `xamarin-test-cloud` and `calabash-cucumber` gems).

I scheduled to fix this!

**Comment by adnxsmob1** [comment]
Thanks @godrei ... when will i have the fix available for me to continue my work?

**Comment by godrei** [comment]
Hi @adnxsmob1,

we released a new version ([v1.0.0](https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-calabash-ios/releases/tag/1.0.0)) with the fix for your issue.

Thanks for the report!
